const $$=s=>document.querySelectorAll(s);
let amount=10000,method="MTN Mobile Money";
$$(".amount").forEach(b=>b.onclick=()=>{$$(".amount").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");amount=+b.dataset.amount;const i=document.querySelector("#customAmount");if(i)i.value=amount});
$$(".methods button").forEach(b=>b.onclick=()=>{$$(".methods button").forEach(x=>x.classList.remove("sel"));b.classList.add("sel");method=b.dataset.method});
const f=document.querySelector("#donationForm");
if(f)f.onsubmit=e=>{e.preventDefault();if(amount<500){alert("Le don minimum est de 500 FCFA.");return}const name=document.querySelector("#donorName")?.value||"Donateur";let d=JSON.parse(localStorage.getItem("pnc_v2_dons")||"[]");d.push({date:new Date().toISOString(),name,amount,method});localStorage.setItem("pnc_v2_dons",JSON.stringify(d));const n=document.querySelector("#donationMsg");n.className="notice success";n.innerHTML="Merci "+name+" ❤️ Don enregistré en mode démonstration. La connexion aux paiements réels sera faite avec les comptes marchands PNC.";};
function admin(){let d=JSON.parse(localStorage.getItem("pnc_v2_dons")||"[]"),t=d.reduce((a,x)=>a+x.amount,0);const a=document.querySelector("#adminTotal"),c=document.querySelector("#adminCount"),tb=document.querySelector("#adminTable");if(a)a.textContent=new Intl.NumberFormat("fr-FR").format(t)+" FCFA";if(c)c.textContent=d.length;if(tb)tb.innerHTML=d.length?d.slice().reverse().map(x=>`<tr><td>${new Date(x.date).toLocaleString("fr-FR")}</td><td>${x.name}</td><td>${new Intl.NumberFormat("fr-FR").format(x.amount)} FCFA</td><td>${x.method}</td></tr>`).join(""):`<tr><td colspan="4">Aucun don enregistré.</td></tr>`}
admin();const r=document.querySelector("#reset");if(r)r.onclick=()=>{localStorage.removeItem("pnc_v2_dons");admin()};
const L={fr:{home:"Accueil",mission:"Notre mission",camp:"Campagnes",stories:"Témoignages",faq:"FAQ",contact:"Contact",donate:"Faire un don"},en:{home:"Home",mission:"Our mission",camp:"Campaigns",stories:"Testimonials",faq:"FAQ",contact:"Contact",donate:"Donate"}};
const lang=document.querySelector("#lang");if(lang)lang.onchange=()=>{$$("[data-i18n]").forEach(x=>{const v=L[lang.value][x.dataset.i18n];if(v)x.textContent=v})};
